version: '2'
services:
  web:
    build: ./web
    tty: true
    links:
      - fpm
      - mysql
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DB_HOST=mysql
      - DB_NAME=filesender
      - DB_USER=filesender
      - DB_PASSWORD=filesender
      - FILESENDER_DOMAIN=localhost
      - SAML_MAIL_ATTR=urn:oid:0.9.2342.19200300.100.1.3
      - SAML_NAME_ATTR=urn:oid:2.16.840.1.113730.3.1.241
      - SAML_UID_ATTR=urn:oid:0.9.2342.19200300.100.1.1

    volumes:
      - filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp
      - ./saml/config.php:/opt/conf.d/simplesamlphp_config.php
      - ./saml/authsources.php:/opt/conf.d/simplesamlphp_authsources.php

  fpm:
    build: ./fpm
    links:
      - mysql
    environment:
      - SMTP_SERVER=smtp.test
      - FILESENDER_DOMAIN=localhost
    volumes:
      - filesender:/opt/filesender
      - simplesaml:/opt/simplesamlphp

  mysql:
    image: 'mysql'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=insecure
      - MYSQL_DATABASE=filesender
      - MYSQL_USER=filesender
      - MYSQL_PASSWORD=filesender
      - MYSQL_ALLOW_EMPTY_PASSWORD='false'
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  filesender:
  simplesaml:
